# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tasks', models.CharField(max_length=100)),
                ('status', models.TextField(max_length=100)),
                ('bday', models.DateField()),
                ('time', models.DateTimeField()),
                ('date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('planned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AP_made', to='login.User')),
            ],
        ),
    ]
