# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoint',
            old_name='Tasks',
            new_name='tasks',
        ),
    ]
